name: "For Dev"

on:
    issues:
        types: [closed]
    pull_request:
        types: [closed]
  
env:
    GODOT_VERSION: 4.4.1
    EXPORT_NAME: watermarked
    PROJECT_PATH: .

jobs:
    export-web:
        permissions: write-all
        name: Web Export
        runs-on: ubuntu-latest
        container:
          image: barichello/godot-ci:4.4.1
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                lfs: true
            - name: Setup
              run: |
                mkdir -v -p ~/.local/share/godot/export_templates/
                mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

            - name: Import Assets
              run: |
                cd $PROJECT_PATH
                godot --headless --verbose --editor --quit
                
            - name: Web Build
              run: |
                mkdir -v -p build/web
                EXPORT_DIR="$(readlink -f build)"
                cd $PROJECT_PATH
                godot --headless --verbose --export-release "Web" "$EXPORT_DIR/web/index.html"

            - name: Upload Artifact
              id: upload_artifact
              uses: actions/upload-artifact@v4
              with:
                name: web
                path: build/web

    publish-on-github-pages:
        permissions: write-all
        needs: export-web
        name: Publishing on Github Pages
        runs-on: ubuntu-latest
        steps:
        - name: Download Web Artifact
          uses: actions/download-artifact@v4
          with:
            name: web
            path: build/web/

        - name: Install rsync 📚
          run: |
            sudo apt-get update && sudo apt-get install -y rsync

        - name: Add coi-service-worker
          run: |
            git clone https://github.com/gzuidhof/coi-serviceworker.git
            mv coi-serviceworker/coi-serviceworker.js build/web/coi-serviceworker.js
            sed -i '3 i <script src="coi-serviceworker.js"></script>' build/web/index.html

        - name: Deploy
          uses: peaceiris/actions-gh-pages@v4
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./build/web
            force_orphan: true
            user_name: "github-ci[bot]"
            user_email: "github-actions[bot]@users.noreply.github.com"
            commit_message: "Publish to gh-pages"